import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/ui/styles.css";
import "./globals.css";
// import "../lib/storyblok";
import { getLatestGlobalNavigation, StoryblokBridge } from "@repo/storyblok";
import { FooterNavigation, HeaderNavigation, Layout } from "@repo/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    // Fetch header navigation data from Storyblok only
  let headerNavigation = null;
  
  try {
    console.log("calling latest global nav")
    const storyblokNav = await getLatestGlobalNavigation(true, 'octoberthree-main');
    if (storyblokNav) {
      headerNavigation = storyblokNav.story.content 
    }
  } catch (error) {
    console.error('Error fetching headerNavigation from Storyblok:', error);
  }
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoryblokBridge>
          <HeaderNavigation headerNavigation={headerNavigation} />
          <main className="grow">{children}</main>
          <FooterNavigation />
        </StoryblokBridge>
      </body>
    </html>
  );
}
