export const o3edgeRedirects = [
  { source: '/insights/5-tips-for-retirement-plan-prospecting.html', destination: '/insights/5-tips-for-retirement-plan-prospecting', permanent: true },
  { source: '/insights/august-annuity-purchase-update-2022.html', destination: '/insights/august-annuity-purchase-update-2022', permanent: true },
  { source: '/insights/checklist-advising-hospital-plan-sponsors.html', destination: '/insights/checklist-advising-hospital-plan-sponsors', permanent: true },
  { source: '/insights/debunking-retirement-plan-prospecting-myths.html', destination: '/insights/debunking-retirement-plan-prospecting-myths', permanent: true },
  { source: '/insights/how-to-differentiate-your-advisory-practice.html', destination: '/insights/how-to-differentiate-your-advisory-practice', permanent: true },
  { source: '/insights/how-to-stand-out-in-financial-advisor-space.html', destination: '/insights/how-to-stand-out-in-financial-advisor-space', permanent: true },
  { source: '/insights/identify-retirement-plan-prospects.html', destination: '/insights/identify-retirement-plan-prospects', permanent: true },
  { source: '/insights/prospecting-with-purpose-case-study.html', destination: '/insights/prospecting-with-purpose-case-study', permanent: true },
  { source: '/insights/retirement-plan-advisory-during-covid-19.html', destination: '/insights/retirement-plan-advisory-during-covid-19', permanent: true },
  { source: '/insights/seventh-circuit-upholds-dol-cybersecurity-subpoena-against-alight-requiring.html', destination: '/insights/seventh-circuit-upholds-dol-cybersecurity-subpoena-against-alight-requiring', permanent: true },

  { source: '/insights//prospecting-with-purpose-case-study.html', destination: '/insights/prospecting-with-purpose-case-study', permanent: true },
  { source: '/insights//identify-retirement-plan-prospects.html', destination: '/insights/identify-retirement-plan-prospects', permanent: true },
  { source: '/insights//5-tips-for-retirement-plan-prospecting.html', destination: '/insights/5-tips-for-retirement-plan-prospecting', permanent: true },
  { source: '/insights//debunking-retirement-plan-prospecting-myths.html', destination: '/insights/debunking-retirement-plan-prospecting-myths', permanent: true },
  { source: '/insights//how-to-stand-out-in-financial-advisor-space.html', destination: '/insights/how-to-stand-out-in-financial-advisor-space', permanent: true },
  { source: '/insights//retirement-plan-advisory-during-covid-19.html', destination: '/insights/retirement-plan-advisory-during-covid-19', permanent: true },
  { source: '/insights//checklist-advising-hospital-plan-sponsors.html', destination: '/insights/checklist-advising-hospital-plan-sponsors', permanent: true },
  { source: '/insights//how-to-differentiate-your-advisory-practice.html', destination: '/insights/how-to-differentiate-your-advisory-practice', permanent: true },

  { source: '/tags/annuity-purchase-update', destination: '/insights?category=annuity-purchase-update', permanent: true },
  { source: '/tags/annuity-purchase-update.html', destination: '/insights?category=annuity-purchase-update', permanent: true },
  { source: '/tags/legislative-update', destination: '/insights?category=legislative-update', permanent: true },
  { source: '/tags/legislative-update.html', destination: '/insights?category=legislative-update', permanent: true },
  { source: '/tags/retirement-plan-prospecting', destination: '/insights?category=retirement-plan-prospecting', permanent: true },
  { source: '/tags/retirement-plan-prospecting.html', destination: '/insights?category=retirement-plan-prospecting', permanent: true },
  { source: '/tags/what-plan-sponsors-want', destination: '/insights?category=what-sponsors-want', permanent: true },
  { source: '/tags/what-plan-sponsors-want.html', destination: '/insights?category=what-sponsors-want', permanent: true },

  { source: '/team/cecily-coia', destination: '/meet-the-team', permanent: true },
  { source: '/team/kara-donahue', destination: '/meet-the-team', permanent: true },
  { source: '/team/aisling-donnelly', destination: '/meet-the-team', permanent: true },
  { source: '/team/robert-fanning', destination: '/meet-the-team', permanent: true },
  { source: '/team/samantha-macgowan', destination: '/meet-the-team', permanent: true },
  { source: '/team/hannah-marohl', destination: '/meet-the-team', permanent: true },
  { source: '/team/emily-misiorowski', destination: '/meet-the-team', permanent: true },
  { source: '/team/ammar-shaheen', destination: '/meet-the-team', permanent: true },
  { source: '/team/larry-sher', destination: '/meet-the-team', permanent: true },
  { source: '/team/madison-walters', destination: '/meet-the-team', permanent: true },
];